name: Alraseen Non Prod Deployment - Azure


on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Add .env variable
        run: |
         echo "NEXT_PUBLIC_API_BASE_URL=https://dev-api-alraseen.azurewebsites.net" > .env
         echo "PORT=3000" >> .env

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build app
        run: CI=false && yarn build

      - name: Deploy prebuilt app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN_NON_PROD }}
          skip_app_build: true
          action: "upload"
          app_location: "/out"          
          repo_token: ${{ secrets.GITHUB_TOKEN }}
  

  
