name: Deploy to Railway Develop

on:
  push:
    branches:
      - develop-ignored

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SVC_ID: 84a627f5-ea6f-42d9-92af-dde86fe2d1a5
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_DEV }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Add environment variables
        run: |
          echo "NEXT_PUBLIC_API_BASE_URL=https://api-dev.alraseen.ae" > .env
          echo "PORT=3000" >> .env

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js static site
        run: yarn build

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy static site to Railway
        run: cd out && railway up --service=${{ env.SVC_ID }} --ci
