name: Deploy to Railway Production

on:
  push:
    branches:
      - main-ignored

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 84a627f5-ea6f-42d9-92af-dde86fe2d1a5
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PROD }}
    steps:
      - uses: actions/checkout@v3
      - name: Add .env variable
        run: echo "NEXT_PUBLIC_API_BASE_URL=https://api.alraseen.ae" > .env

      - run: railway up --service=${{ env.SVC_ID }} --ci
